# Generated by Django 4.1.3 on 2022-12-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.IntegerField(max_length=70)),
                ('last_name', models.IntegerField(max_length=70)),
            ],
        ),
        migrations.DeleteModel(
            name='employee',
        ),
    ]
